# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do    
  desc 'Fetch certificates and provisioning profiles'
  lane :certificates do
    match(app_identifier: 'org.hnf.prestapp')
  end

  lane :bump_build_version do
    increment_build_number(xcodeproj: './ios/AppPresta.xcodeproj')
    commit_version_bump(message: 'Bump iOS build', xcodeproj: './ios/AppPresta.xcodeproj')
    git_pull
    push_to_git_remote
  end
  
  lane :build do
    cocoapods(podfile: "./ios/Podfile")
    certificates
    bump_build_version
    gym(
      scheme: 'AppPresta', 
      clean: true, 
      workspace: './ios/AppPresta.xcworkspace', 
      export_method: 'development', 
      output_directory: './builds'
    )
  end

  lane :beta do
    bump_build_version
    build
    appcenter_upload(
      api_token: ENV["APPCENTER_API_TOKEN"],
      owner_name: ENV["APPCENTER_OWNER_NAME"],
      owner_type: ENV["APPCENTER_OWNER_TYPE"],
      app_name: ENV["APPCENTER_APP_NAME_IOS"],
      ipa: ENV["IPA_PATH"]
    )
  end

end

platform :android do
  desc 'Build the Android application.'
  lane :build do
    gradle(task: 'clean', project_dir: 'android/')
    gradle(task: 'assemble', build_type: 'release', project_dir: 'android/')
  end

  desc 'Build and upload to App Center.'
  lane :beta do
  build
  appcenter_upload(
      api_token: ENV["TEST_APPCENTER_API_TOKEN"],
      owner_name: ENV["TEST_APPCENTER_OWNER_NAME"],
      app_name: ENV["APPCENTER_APP_NAME"],
      apk: ENV["APPCENTER_DISTRIBUTE_APK"]
      )
  end
end